# Generated by Django 4.0.3 on 2022-03-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompressedECG",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("original_size", models.IntegerField()),
                ("data", models.FileField(upload_to="")),
            ],
        ),
    ]
