# Generated by Django 4.0.3 on 2022-03-14 15:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ecgzip', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DecompressedECG',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False)),
                ('data', models.FileField(upload_to='decompressed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='compressedecg',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='compressedecg',
            name='data',
            field=models.FileField(upload_to='compressed'),
        ),
    ]
